title: Gayathri Annem
email: annemgacs@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog, which I developed to showcase my work on algorithms and provide solutions to some LeetCode problems.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  annemgacs

# Build settings
theme: minima
plugins:
  - jekyll-feed

#[jekyll]: https://jekyllrb.com/
